
Vagrant.configure("2") do |config|

config.vm.box = "generic/centos9s"

config.vm.provider "vmware_desktop" do |v|

  v.gui = true
  v.verify_vmnet = true
  v.linked_clone = false
  v.vmx["memsize"] = "8192"
  v.vmx["numvcpus"] = "4"

  end
end